Repository prajnasuresh/algorithms, pull requests merged in 2021-10, with the labels that each got.

#1 Binary Search Added
  binary_search.py
Labels: hacktoberfest-accepted

#6 Create linear_search.js
  searching/linear_search.js
Labels: hacktoberfest-accepted, hacktober-accepted

#11 Added Binary Exponentiation Algo
  Binary Exponentiation/binaryexpo.cpp
Labels: hacktober-accepted

#12 binary_search added in c language
  a.out
  demo.js
  searching/binary_search.c
Labels: hacktober-accepted

#13 added searching files
  searching/InterpolationSearch.cpp
  searching/LinearSearch.cpp
Labels: hacktober-accepted

#16 Added DFS (Depth First Search) Algorithm
  Graph Algorithms/dfs.cpp
Labels: hacktober-accepted

#19 added merge sort algo python
  sortings/merge_sort.py
Labels: hacktober-accepted

#21 Fibanocci Numbers Added
  fibanocii/fibonacii.py
Labels: hacktober-accepted
